image: "python:3.10"

stages:
  - "lint"
  - "test"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python --version  # For debugging
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

LINT:
  stage: lint
  script:
    - poetry run task lint

TEST:
  stage: test
  script:
    - poetry run task test
  artifacts:
    name: coverage-$CI_PIPELINE_ID
    expose_as: coverage-$CI_PIPELINE_ID
    paths:
      - htmlcov
    expire_in: 30 days
    # public: true
  
