image: "python:3.10"

stages:
  - lint
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python --version  # For debugging
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

LINT:
  stage: lint
  script:
    - poetry run task lint

TEST_COVERAGE:
  stage: test
  script:
    - poetry run task test
  artifacts:
    name: coverage-$CI_PIPELINE_ID
    expose_as: code-coverage
    paths:
      - htmlcov
    expire_in: 30 days
    # public: true

TEST_DOCS:
  stage: test
  script:
  - mkdocs build --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH


PAGES:
  stage: deploy
  script:
  - mkdocs build --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
